FROM oven/bun:1@sha256:0733e50325078969732ebe3b15ce4c4be5082f18c4ac1a0f0ca4839c2e4e42a7 AS builder

WORKDIR /build/web
COPY web/package.json web/bun.lock ./
RUN bun install --frozen-lockfile
COPY web ./
COPY VERSION /build/VERSION
RUN DISABLE_ESLINT_PLUGIN=true VITE_REACT_APP_VERSION=$(cat /build/VERSION) bun run build

FROM nginx:1.27-alpine

COPY deploy/nginx.split.conf /etc/nginx/nginx.conf
COPY --from=builder /build/web/dist /usr/share/nginx/html
RUN chmod -R a+rX /usr/share/nginx/html

EXPOSE 3000
